# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='session_key',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
