# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_auto_20170523_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join',
            old_name='user',
            new_name='email',
        ),
    ]
